#!/bin/sh
# Copyright (c) 2022 Ashlen <eurydice@riseup.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

set -eu

umask 077

/usr/bin/perl /etc/sysadm/rotate-files /var/prosody/prosody-backup.sqlite.gz 5

# Just in case.
/bin/chmod 400 /var/prosody/prosody-backup.sqlite.gz.?
/usr/sbin/chown _prosody:_prosody /var/prosody/prosody-backup.sqlite.gz.?

/usr/bin/install -g _prosody -o _prosody -m 600 -- /dev/null /var/prosody/prosody-backup.sqlite.gz

/usr/sbin/rcctl stop prosody

/usr/bin/doas -u _prosody /bin/sh -c \
	'cd /var/prosody \
		&& sqlite3 prosody.sqlite .dump \
		| gzip -c > /var/prosody/prosody-backup.sqlite.gz'

/bin/chmod 400 /var/prosody/prosody-backup.sqlite.gz

/usr/sbin/rcctl start prosody
