#!/bin/sh
# Copyright (c) 2022 Ashlen <eurydice@riseup.net>

# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Sync Upload Date and Access Time
#
# This is a wrapper script for sudat.


err() {
  printf '%s\n' "$*" >&2
  exit 1
}


usage() {
  err "${0##*/} [-t] [directory of videos]
-t: threads (parallelization)

If sudat is located somewhere else, use SUDAT=/path/to/sudat ${0##*/} ..."
}


list_video_files() {
  find . -type f \( -name '*.webm' -o -name '*.mp4' -o -name '*.mkv' \) -print0
}


xargs_handler() {
  if [ -n "${THREADS}" ]; then
    xargs -0 -n 1 -P "${THREADS}" -- "${SUDAT}"

  else
    xargs -0 -n 1 -- "${SUDAT}"

  fi
}


while getopts t: opt; do
  case "${opt}" in
    t) THREADS="${OPTARG}" ;;
    *) usage               ;;
  esac
done

shift $((OPTIND - 1))

case "${THREADS}" in
  *[!0-9]*) err '-t only accepts integers.' ;;
esac


[ -z "$1" ] && usage
[ -d "$1" ] || err "$1 is not a directory."
cd "$1" || err "Unable to change directory to $1."


: "${SUDAT:=/etc/sysadm/sudat}"
list_video_files | xargs_handler
